server:
  port: 8083
spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    
  web:
    resources:
      static-locations: classpath:/static/
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ep-bitter-firefly-aoggwfa4-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_h9fzAUTYaWM1&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_h9fzAUTYaWM1
    dbcp2:
      initial-size: 15
      max-total: 40
      min-idle: 10
      test-on-borrow: true
      validation-query: SELECT 1
      
       
  application:
    name: baseball-boot
